echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOkxxdoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooodxxkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMMMMMMMMMWNKOxoc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:loxOKNWMMMMMMMMMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMMMMMMWKkdc;,,,,,''.....................................................................................''',,,,,;cdOXWMMMMMMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMMMWKkl:,,,,'....                                                                                          ...'',,,,:okXWMMMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMNOo:,,,''..                                                                                                    ..'',,,:d0NMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMWNkl;,,,'..                                                                                                          ..',,,;lONMMMMMMMMMMMM";
echo "MMMMMMMMMMNOl;,,'..                                                                                                                ..',,;l0WMMMMMMMMMM";
echo "MMMMMMMMWKd;,,'..                                                                                                                    ..,,,;dXMMMMMMMMM";
echo "MMMMMMMWOc,,,'.                                                         ..................                                             .',,,c0WMMMMMMM";
echo "MMMMMMNx:,,'.                                                   .....''',,,,,,,,,,,,,,,,,,'''....                                        .',,:kNMMMMMM";
echo "MMMMMNx;,,'.                                               ...'',,,,,,'''................''',,,,,''...                                    .',,;kNMMMMM";
echo "MMMMNx;,,'.                                            ...',,,,,'.....                      ....'',,,,'...                                 .',,:kWMMMM";
echo "MMMWO:,,'.                                          ..',,,,'....                                  ...',,,,'..                               .',,c0WMMM";
echo "MMMKl,,,.                                        ..',,,'....   ....................                   ...',,,'..                             .,,,oXMMM";
echo "MMWx;,,'.                                      ..',,,'.......''',,,,,,,,,,,,,,,,,,,''....                 ..',,,'..                          .',,;kWMM";
echo "MMXl,,,.                                     .',,,''...'',,,,,'''................''',,,,,''...               ..',,'..                         .,,,oXMM";
echo "MMO:,,'.                                   ..,,,,'''',,,''....                      ....'',,,,'..              ..',,'..                       .',,c0MM";
echo "MWk;,,'.                                  .',,,,,,,,,'..                                  ..'',,,'..             ..',,'..                     .',,:OWM";
echo "MWx;,,.                                 .',,,,,,,,'..                                         .',,,'.              ..',,'.                    .',,;kWM";
echo "MWx,,,.                              ...',,,,,,,'..                                             ..',,'.              .',,,.                    ',,;kWM";
echo "MWx,,,.                           ..',,,,,,,,,,..                                                 .',,,..              .,,,'.                  ',,;kWM";
echo "MWx,,,.                        ..',,,'..',,,,'.                                                     .,,,'.              .',,'.                 ',,;kWM";
echo "MWx,,,.                      ..',,'..  .',,'.                                                        .',,'.              .',,'.                ',,;kWM";
echo "MWx,,,.                     .',,'..   .',,'.                                                          .',,'.              .',,'.               ',,;kWM";
echo "MWx,,,.                    .',,'.    .',,'.                                                            .',,'.              .',,'.              ',,;kWM";
echo "MWx,,,.                   .,,,..    .',,'.                                                              .,,,.               .',,'.             ',,;kWM";
echo "MWx,,,.                  .,,,.     .',,'.                                                                ',,'.               .,,,'             ',,;kWM";
echo "MWx,,,.                 .,,,.     .',,'.                                                                 .',,'                .,,,.            ',,;kWM";
echo "MWx,,,.                .',,'.     .,,,.            .........                                              .,,'.               .',,'.           ',,;kWM";
echo "MWx,,,.                .,,,.     .',,'.         ..',,,,,,,,,''.                                           .,,,.                .,,,.           ',,;kWM";
echo "MWx,,,.               .',,'.     ',,'.        ..,,,'.......',,,'.                                         .',,'.               .',,'.          ',,;kWM";
echo "MWx,,,.               .,,,.     .',,'        .',,,..        .',,'.                                        .',,'.                .,,,.          ',,;kWM";
echo "MWx,,,.               .,,,.     .,,,.       .',,'.           .',,'.                                        .,,'.                .',,.          ',,;kWM";
echo "MWx,,,.               .,,,.     ',,'.       .,,,.             .,,'.                                        ',,'.                .',,'.         ',,;kWM";
echo "MWx,,,.               .,,,.    .',,'.      .',,'.            .',,'.                                       .',,'.                 .,,,.         ',,;kWM";
echo "MWx,,,.               .,,,.    .',,'       .,,,.            .',,,.                                        .',,.                  .,,,.         ',,;kWM";
echo "MWx,,,.               .',,'.   .',,.       .,,'.  .'.......',,,'.                                         .,,,.                  .,,,.         ',,;kWM";
echo "MWx,,,.                .,,,.   .,,,.      .',,'. .',,,,,,,,,''.                                          .',,'.                  .,,,.         ',,;kWM";
echo "MWx,,,.                 .,,'. .',,'.      .',,'.   ..........                                           .',,'.                   .',,.         ',,;kWM";
echo "MWx,,,.                 ..,,,'',,,.       .',,'                                                        .',,'.                    .,,,.         ',,;kWM";
echo "MWx,,,.                   .',,,,,'.       .',,'                                                       .',,'.                     .,,,.         ',,;kWM";
echo "MWx,,,.                    .',,,'.        .',,'                                                     ..,,,'.                      .,,,.         ',,;kWM";
echo "MWx,,,.                    .',,'.          ....                                                    .',,'.                        ',,'.         ',,;kWM";
echo "MWx,,,.                   .',,'.                                                                 ..,,,'.                        .',,'.         ',,;kWM";
echo "MWx,,,.                 ..,,,'.                                                                ..',,'.                          .,,,.          ',,;kWM";
echo "MWx,,,.                .',,'.                                                                ..,,,'..                           .,,'.          ',,;kWM";
echo "MWx,,,.              ..,,,'.                                                               .',,,'..                            .',,'           ',,;kWM";
echo "MWx,,,.             .',,,.               ..                                             ..',,,'.                               .,,,.           ',,;kWM";
echo "MWx,,,.            .',,'.              ..''..                                        ..',,,'..                                .',,'.           ',,;kWM";
echo "MWx,,,.           .',,'.               ..',,''..                                 ...',,,'..                                   .,,,.            ',,;kWM";
echo "MWx,,,.          .',,'.                  ..',,,''...                        ....',,,,'...                                    .',,.             ',,;kWM";
echo "MWx,,,.          .,,,.                      ..'',,,,''...................''',,,,,'...                                       .',,'.             ',,;kWM";
echo "MWx,,,.         .',,'.         ......          ....'',,,,,,,,,,,,,,,,,,,,,'''....                                           .,,,.             .',,;kWM";
echo "MWx,,,.         .,,,.       .''',,,,,''.             .....................                                                 .,,,.              .',,;kWM";
echo "MWx;,,'         .,,'.     .',,,'.....''.                                                                                  .',,'.              .',,;kWM";
echo "MWO:,,'.        .,,'.    .,,,'.                                                                                          .',,'.               .',,:OMM";
echo "MMKc,,'.        .,,,.   .,,,.                                                                                           .',,'.                .,,,lKMM";
echo "MMNd,,,.         .,,'. .',,.                                                                                           .',,'.                 ',,,xNMM";
echo "MMW0:,,'.         .','..,,..                                                                                          .',,'.                 .,,,c0MMM";
echo "MMMNx;,,'.         .',,,,'.                                                                                          .',,'.                 .',,;xWMMM";
echo "MMMMXo,,,.           ..','                                                                                          .',,'.                 .',,,oXMMMM";
echo "MMMMMKl,,,..           ...                                                                                         .,,,'.                 .',,,oKMMMMM";
echo "MMMMMWKl,,,'.                                                                                                     ..',..                 .',,,oKMMMMMM";
echo "MMMMMMMXo;,,'.                                                                                                       .                  .',,;dXMMMMMMM";
echo "MMMMMMMMNk:,,,'.                                                                                                                      .',,,ckNMMMMMMMM";
echo "MMMMMMMMMW0o;,,'..                                                                                                                  ..,,,;oKWMMMMMMMMM";
echo "MMMMMMMMMMMNOl;,,,'.                                                                                                              .',,,;o0NMMMMMMMMMMM";
echo "MMMMMMMMMMMMMNOo;,,,'..                                                                                                        ..',,,:o0NMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMMWKxc;,,,''...                                                                                              ...'',,,;lxKWMMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMMMMMN0xl;,,,,''......                                                                                ......',,,,,:lx0NWMMMMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMMMMMMMMNKOdl:;,,,,,,,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',,,,,,,;clxOKWMMMMMMMMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMMMMMMMMMMMMWX0Oxdolc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::clodxOKXWMMMMMMMMMMMMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXKKKK0000000000000000000000000000000000000000000000000000000000000000000000000KKXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM";
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM";